name: python-learn2trust
channels:
  - pytorch
  - conda-forge
  - plotly
  - defaults
dependencies:
  - imageio
  - matplotlib
  - numpy
  - pillow
  - plotly
  - pytorch
  - scikit-image
  - scikit-learn
  - scipy
  - torchvision
  - pandas
  - st-annotated-text
  - streamlit
  - typing
  - collections
  - ipywidgets
  
